export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_DATA = 'AUTH_DATA';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_QUESTIONS = 'ADD_QUESTIONS';
export const SET_SELECTED_QUESTIONS = 'ADD_SELECTED_QUESTIONS';

export const ADD_TEMPLATES = 'ADD_TEMPLATE';
export const SET_SELECTED_TEMPLATES = 'SET_SELECTED_TEMPLATES';
export const REMOVE_TEMPLATE = 'REMOVE_TEMPLATE';

export const ADD_RESULT_TEMPLATES = 'ADD_RESULT_TEMPLATE';